version: "3"

services:
  chatto:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
            device_ids: ['all']